version: '3.8'

services:
  elastic:
    image: elasticsearch:7.9.1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data:rw
    environment:
      - cluster.name=laradock-cluster
      - node.name=laradock-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=laradock-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    environment:
      FLASK_APP: project/__init__.py
      SQL_HOST: db
      SQL_PORT: 3306
      APP_FOLDER: /home/app/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000:5000
    depends_on:
      - elastic

volumes:
  elasticsearch-data:
    driver: local